AWSTemplateFormatVersion: 2010-09-09
Description: 'Bastion Host in AutoSG with two subnet'
#-------------------------------Parameters----------------------------------
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

          #--------  For VPC -------------

  VpcCIDR:
    Description: IP range for this VPC
    Type: String
    Default: 10.1.0.0/16

  PublicSubnetAcidr:
    Description:  IP range  for the public subnet A
    Type: String
    Default: 10.1.11.0/24

  PublicSubnetBcidr:
    Description:  IP range  for the public subnet B
    Type: String
    Default: 10.1.21.0/24

        #--------  For EC2 -------------

  LatestAMIid:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'


#-------------------------------Resources----------------------------------

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref EnvironmentName, -VPC ]]

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref EnvironmentName, -IGW ]]

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

          #--------------- Creation subnet AZ - A and B ----------------------

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: !Ref PublicSubnetAcidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Public-SubnetA


  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs ]
      CidrBlock: !Ref PublicSubnetBcidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Public-SubnetB


      #--------------- Creat Public Route Table ----------------------

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetA

  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetB

#-------------------------------Resources----------------------------------
Outputs:
  Region:
    Description: "Current Region"
    Value:
      Ref: "AWS::Region"
  LastAMI:
   Description: "Last Amazon AMI"
   Value: !Ref LatestAMIid
